### ISSUE TITLE
Job Status Enum Ambiguity

### ISSUE THREAD

**Issue by gregorhaywood** [CS3099JH2017/cs3099jh#26]
The GET Status request returns one of four values in the status field of its success response body. From my understanding, **running** means training is still happening, **failed** suggests an error prevented training from producing a usable model, and **complete** means the training finished (either automatically or due to an interrupt) and has produced a model that can be used with GET Prediction. 

I cannot find a use for **cancelled** as a response, as DELETE will remove the model entirely, so GET Status will return _404 job\_not\_found_, and DELETE Stop Training will produce a usable model that may be (depending on implementation and timing) identical to an uninterrupted model, so should return **complete**. 

Can we either clearly define the use of **cancelled** or remove it from the protocol?

**Comment by db213** [comment]
Agree, there doesn't seem to be a use for cancelled. If no one disagrees, I'll remove it.
